CREATE DATABASE usersDB;
USE usersDB;

CREATE TABLE Users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE Captchas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    text VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE EVENT IF NOT EXISTS `delete_old_captchas`
ON SCHEDULE EVERY 1 DAY STARTS CONCAT(ADDDATE(CURDATE(), INTERVAL 1 DAY), ' 06:00:00')
DO
  DELETE FROM Captchas WHERE created_at < DATE_SUB(NOW(), INTERVAL 30 MINUTE);